/*
 * Copyright © 2015 by YuXiang Chen 
 * All rights reserved
*/

using System.Collections.Generic;

namespace Ycql.Interfaces
{
	/// <summary>
	/// Allows the Sql statement generated by the builder to do Sql join
	/// </summary>
	/// <typeparam name="T">The type of the class which supports join operation</typeparam>
	internal interface IJoinable<T>
	{
		/// <summary>
		/// Joins one or more tables to the statement
		/// </summary>
		/// <param name="joinDefinitions">Join definitions to be joined</param>
		/// <returns>A reference to this instance after the join definitions has been added to the join list</returns>
		T Join(params JoinDefinition[] joinDefinitions);
	}
}
